### PR TITLE
Auth prisma

### PR DESCRIPTION
**Pull request by KYogesh20**
implement create and update user

### CODE REVIEW

**Comment by ujjwal-kr** [comment]
donot merge without the last review of mine

**Review by PhantomKnight287 — COMMENTED** [review]
Please fix the typo in `User` model, it should be `createdAt` instead of `createAt`

**Review by PhantomKnight287 — COMMENTED** [review]
Please do something with the `result` variable in `auth.service.ts` on line 16 and 35

**Review by ujjwal-kr — APPROVED** [review]
Chalo, make sure to maintain this standard before PR from next time.

**Pull request merged**
